exclude: ".yarn/|yarn.lock|\\.min\\.(css|js)$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: forbid-sourcemap
        name: Check for sourceMappingURL
        description: Ensures no files containing sourceMappingURL are committed
        entry: sourceMappingURL
        language: pygrep
        types_or: [javascript, css]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.24.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.2"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.8"
    hooks:
      - id: ruff
        args: [--unsafe-fixes]
      - id: ruff-format
  - repo: https://github.com/biomejs/pre-commit
    rev: "v2.0.0-beta.2"
    hooks:
      - id: biome-check
        args: [--unsafe]
        exclude: "static"
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.5.1
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
